<a href="https://colab.research.google.com/github/pavss/python2/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #import numpy

**Exercise 1**

In [3]:
ages_list = [7,9,65,33,85,99] #generate 1D numpy array
print(ages_list)

[7, 9, 65, 33, 85, 99]


In [11]:
ages = np.array(ages_list)
print(type(ages))
print(ages)

<class 'numpy.ndarray'>
[ 7  9 65 33 85 99]


In [12]:
print(ages)
print("Size:\t" , ages.size)
print("Shape:\t", ages.shape)

[ 7  9 65 33 85 99]
Size:	 6
Shape:	 (6,)


In [13]:
ZeroArr = np.zeros(5)
print(ZeroArr)

[0. 0. 0. 0. 0.]


**Multi-dimensional **

In [63]:
matrix = np.array([[1,2,4], [2,3,0], [0,5,1]])
print("matrix:\t", matrix)
print("size:\t", matrix.size)
print("shape:\t", matrix.shape)

matrix:	 [[1 2 4]
 [2 3 0]
 [0 5 1]]
size:	 9
shape:	 (3, 3)


In [6]:
# 3 x 3 = 1 x 9 = 9 x 1
matrix = matrix.reshape(9,1)
print("matrix:\t", matrix)
print("size:\t", matrix.size)
print("shape:\t", matrix.shape)

matrix:	 [[1]
 [2]
 [4]
 [2]
 [3]
 [0]
 [0]
 [5]
 [1]]
size:	 9
shape:	 (9, 1)


**Array generation**

In [26]:
five_times_table = np.arange(0, 20, 2)
five_times_table

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
five_spaced = np.linspace(0,20,6)
print(five_spaced)

[ 0.  4.  8. 12. 16. 20.]


In [22]:
twoArr = np.repeat(3, 9)
print(twoArr)

[3 3 3 3 3 3 3 3 3]


In [23]:
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Operations**

In [24]:
five_times_table

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
print("1:", 1 * five_times_table)
print("2:", 5 + five_times_table)
print("3:", five_times_table - 5)
print("4:", five_times_table/2)
print("5:", five_times_table **2)
print("6:", five_times_table < 20)

1: [ 0  2  4  6  8 10 12 14 16 18]
2: [ 5  7  9 11 13 15 17 19 21 23]
3: [-5 -3 -1  1  3  5  7  9 11 13]
4: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
5: [  0   4  16  36  64 100 144 196 256 324]
6: [ True  True  True  True  True  True  True  True  True  True]


**speed test**

In [31]:
mylist = list(range(0,300,6))
mylist

[0,
 6,
 12,
 18,
 24,
 30,
 36,
 42,
 48,
 54,
 60,
 66,
 72,
 78,
 84,
 90,
 96,
 102,
 108,
 114,
 120,
 126,
 132,
 138,
 144,
 150,
 156,
 162,
 168,
 174,
 180,
 186,
 192,
 198,
 204,
 210,
 216,
 222,
 228,
 234,
 240,
 246,
 252,
 258,
 264,
 270,
 276,
 282,
 288,
 294]

In [33]:
five_times_table_lge = np.arange(0,300,6)
five_times_table_lge

array([  0,   6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72,
        78,  84,  90,  96, 102, 108, 114, 120, 126, 132, 138, 144, 150,
       156, 162, 168, 174, 180, 186, 192, 198, 204, 210, 216, 222, 228,
       234, 240, 246, 252, 258, 264, 270, 276, 282, 288, 294])

In [34]:
%timeit five_times_table_lge + 3

890 ns ± 2.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [36]:
%timeit [e + 3 for e in mylist]

3 µs ± 48.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [37]:
words = np.array(["ten", "nine", "eight", "seven", "six"])
print(np.isin(words, 'e'))
print("e in words")
["e" in word for word in words]

[False False False False False]
e in words


[True, True, True, True, False]

**Transpose**

In [38]:
matrix.shape = (3,3)
print(matrix, "\n")
print(matrix.T)

[[1 2 4]
 [2 3 0]
 [0 5 1]] 

[[1 2 0]
 [2 3 5]
 [4 0 1]]


Data Types
**Exercise 2**

In [39]:
matrix.dtype

dtype('int64')

In [40]:
ages_with_strings = np.array(['1', '3', '6', '10', '20', '40'])
ages_with_strings

array(['1', '3', '6', '10', '20', '40'], dtype='<U2')

In [41]:
print(ages_with_strings.astype(float))

[ 1.  3.  6. 10. 20. 40.]


In [42]:
matrix.shape = (9,1)
print(matrix, "\n")
print(matrix.T)

[[1]
 [2]
 [4]
 [2]
 [3]
 [0]
 [0]
 [5]
 [1]] 

[[1 2 4 2 3 0 0 5 1]]


In [43]:
print(ages_with_strings.astype(bool))

[ True  True  True  True  True  True]


**Exercise 3**
Array slicing operations

In [45]:
arr0 = np.zeros(50)
arr0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
arr2 = np.full(20,2)
arr2

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [49]:
arrpi = np.arange(start=0, stop=6.28, step=0.1)
arrpi

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2])

In [50]:
arrpi[:5]

array([0. , 0.1, 0.2, 0.3, 0.4])

In [52]:
arrpi[-3:]

array([6. , 6.1, 6.2])

In [53]:
arrpi[4:8]

array([0.4, 0.5, 0.6, 0.7])

In [54]:
reverse_arrpi = np.flip(arrpi)
reverse_arrpi

array([6.2, 6.1, 6. , 5.9, 5.8, 5.7, 5.6, 5.5, 5.4, 5.3, 5.2, 5.1, 5. ,
       4.9, 4.8, 4.7, 4.6, 4.5, 4.4, 4.3, 4.2, 4.1, 4. , 3.9, 3.8, 3.7,
       3.6, 3.5, 3.4, 3.3, 3.2, 3.1, 3. , 2.9, 2.8, 2.7, 2.6, 2.5, 2.4,
       2.3, 2.2, 2.1, 2. , 1.9, 1.8, 1.7, 1.6, 1.5, 1.4, 1.3, 1.2, 1.1,
       1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0. ])

In [55]:
arrpi[0::4]

array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8,
       5.2, 5.6, 6. ])

In [56]:
arrpi[-1::-2]

array([6.2, 6. , 5.8, 5.6, 5.4, 5.2, 5. , 4.8, 4.6, 4.4, 4.2, 4. , 3.8,
       3.6, 3.4, 3.2, 3. , 2.8, 2.6, 2.4, 2.2, 2. , 1.8, 1.6, 1.4, 1.2,
       1. , 0.8, 0.6, 0.4, 0.2, 0. ])

**Exercise 4**

In [57]:
np.array([1.65432, 5.98765]).round(2)


array([1.65, 5.99])

In [58]:
nums = np.arange(0, 4, 0.2555)

In [59]:
print("min = ", np.min(nums).round(2))
print("max = ", np.max(nums).round(2))
print("sum = ", np.sum(nums).round(2))
print("mean = ", np.mean(nums).round(2))
print("median = ", np.median(nums).round(2))
print("var = ", np.var(nums).round(2))
print("std = ", np.std(nums).round(2))

min =  0.0
max =  3.83
sum =  30.66
mean =  1.92
median =  1.92
var =  1.39
std =  1.18


**Exercise 5**

In [61]:
dice = np.random.choice([1,2,3,4,5,6], 10)
dice

array([4, 2, 1, 1, 1, 3, 2, 5, 6, 5])

In [62]:
coin = np.random.choice(["H", "H","T"],10)
coin

array(['T', 'H', 'T', 'T', 'H', 'H', 'H', 'H', 'H', 'H'], dtype='<U1')